services:
  mysql:
    image: mysql:8.0
    container_name: techstore_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: product_inventory
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
